name: MastJaipur Daily Post
on:
  schedule:
    # 10:10 PM IST is 4:40 PM UTC (16:40)
    - cron: '40 16 * * *'
  workflow_dispatch: 

jobs:
  build-and-post:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push image to repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install google-genai requests pillow

      - name: Run News Script
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          IG_TOKEN: ${{ secrets.IG_TOKEN }}
        run: python main.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          keep_files: true